<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCUs4ijf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCUs4ijf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCUs4ijf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCUs4ijf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCUs4ijf\App_KernelDevDebugContainer([
    'container.build_hash' => 'CUs4ijf',
    'container.build_id' => '58925184',
    'container.build_time' => 1705510612,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCUs4ijf');
